### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ar06x** [mathmakgakpak/Node-OWOP#8]
Able to draw over pixels that are the same color when using setpixel, or using calc bot (Lol)

**Comment by mathmakgakpak** [comment]
and?

**Comment by BanThoncc** [comment]
h

**Comment by BanThoncc** [comment]
~~ur mom~~

**Comment by ar06x** [comment]
This is an issue for some people. H

**Comment by mathmakgakpak** [comment]
I can fix it really fast but im lazy
